// resources/js/Pages/Dashboard.vue
<template>
  
  
  <AuthenticatedLayout :user="auth.user">
    <Head title="Stracker" />
    <div class="min-h-screen w-full flex flex-col md:flex-row bg-gray-50 text-gray-900">
      <!-- Sidebar menu -->
      <aside class="w-full md:w-56 flex md:flex-col flex-row gap-2 md:gap-4 items-stretch min-h-[4rem] md:min-h-[32rem] justify-start bg-white border-b md:border-b-0 md:border-r border-gray-200 p-2 md:p-4 sticky top-0 z-20">
        <button
          :class="['btn btn-outline', tab === 'dashboard' ? 'btn-primary text-white' : '']"
          @click="tab = 'dashboard'"
        >
          Dashboard
        </button>
        <button
          :class="['btn btn-outline', tab === 'transactions' ? 'btn-primary text-white' : '']"
          @click="tab = 'transactions'"
        >
          Recent Transactions
        </button>
        <button
          class="btn btn-accent text-white"
          @click="showAddTransaction = true"
        >
          Add Transaction
        </button>
        <form method="POST" :action="route('logout')" class="md:mt-auto">
          <button
            type="submit"
            class="btn btn-error text-white font-bold hover:bg-red-700 transition-colors duration-150"
          >
            Logout
          </button>
        </form>
      </aside>
      <!-- Main content -->
      <main class="flex-1 space-y-8 px-2 sm:px-4 md:px-8 py-4 md:py-8 w-full">
        <template v-if="tab === 'dashboard'">
          <!-- 1. Summary Cards -->
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 w-full">
            <div class="stat bg-white shadow rounded-xl p-6 flex flex-col items-center">
              <div class="stat-title text-gray-700">Total Income</div>
              <div class="stat-value text-green-600 text-3xl font-bold">₱{{ summary.income }}</div>
            </div>
            <div class="stat bg-white shadow rounded-xl p-6 flex flex-col items-center">
              <div class="stat-title text-gray-700">Total Expenses</div>
              <div class="stat-value text-red-600 text-3xl font-bold">₱{{ summary.expense }}</div>
            </div>
            <div class="stat bg-white shadow rounded-xl p-6 flex flex-col items-center">
              <div class="stat-title text-gray-700">Total Revenue</div>
              <div class="stat-value text-blue-600 text-3xl font-bold">₱{{ summary.balance }}</div>
            </div>
          </div>
          <!-- Line chart for total income vs total expense -->
          <div class="card bg-white shadow rounded-xl mb-6 w-full">
            <div class="card-body p-4 md:p-6">
              <h3 class="font-bold mb-4 text-lg text-blue-600">Income vs Expense Over Time</h3>
              <div class="w-full" style="min-height: 220px; height: 30vw; max-height: 340px;">
                <LineChart :data="lineData" />
              </div>
            </div>
          </div>
          <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 w-full">
            <!-- 3. Category Breakdown Diagram (Pie Chart) -->
            <div class="card bg-white shadow rounded-xl md:col-span-2 h-96 p-4 md:p-6 flex flex-col items-center justify-center w-full">
              <h3 class="font-bold mb-4 text-lg text-center text-purple-600">Category Breakdown</h3>
              <div v-if="pieChartData.length > 0" class="w-full" style="min-height: 220px; height: 30vw; max-height: 340px;">
                <PieChart :data="pieChartData" />
              </div>
              <p v-else class="text-gray-500 mt-10">Add transactions to see the diagram</p>
            </div>
          </div>
        </template>
        <template v-else-if="tab === 'transactions'">
          <div class="card bg-white shadow rounded-xl overflow-x-auto w-full">
            <div class="card-body p-4 md:p-6">
              <h3 class="font-bold mb-4 text-lg text-indigo-600">Recent Transactions</h3>
              <!-- Filter Form -->
              <div class="mb-4 p-2 md:p-4 bg-gray-100 rounded-lg">
                <h4 class="font-semibold mb-2 text-gray-700">Filter Transactions</h4>
                <form class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-2 md:gap-4" @submit.prevent="applyFilters">
                  <div class="form-control">
                    <InputLabel value="Category" htmlFor="category_filter" />
                    <select
                      id="category_filter"
                      name="category"
                      class="select select-bordered w-full text-black bg-white"
                      v-model="filters.category"
                    >
                      <option value="">All Categories</option>
                      <option value="Food">Food</option>
                      <option value="Salary">Salary</option>
                      <option value="Rent">Rent</option>
                      <option value="Leisure">Leisure</option>
                      <option value="Bills">Bills</option>
                      <option value="Transportation">Transportation</option>
                      <option value="Utilities">Utilities</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div class="form-control">
                    <InputLabel value="Type" htmlFor="type_filter" />
                    <select
                      id="type_filter"
                      name="type"
                      class="select select-bordered w-full text-black bg-white"
                      v-model="filters.type"
                    >
                      <option value="">All Types</option>
                      <option value="income">Income</option>
                      <option value="expense">Expense</option>
                    </select>
                  </div>
                  <div class="form-control">
                    <InputLabel value="From Date" htmlFor="date_from" />
                    <input
                      id="date_from"
                      name="date_from"
                      type="date"
                      class="input input-bordered w-full text-black bg-white"
                      v-model="filters.date_from"
                    />
                  </div>
                  <div class="form-control">
                    <InputLabel value="To Date" htmlFor="date_to" />
                    <input
                      id="date_to"
                      name="date_to"
                      type="date"
                      class="input input-bordered w-full text-black bg-white"
                      v-model="filters.date_to"
                    />
                  </div>
                  <div class="form-control sm:col-span-2 md:col-span-4 flex gap-2 flex-wrap">
                    <PrimaryButton type="submit" class="btn-sm">
                      Apply Filters
                    </PrimaryButton>
                    <button
                      type="button"
                      class="btn btn-ghost btn-sm"
                      @click="clearFilters"
                    >
                      Clear Filters
                    </button>
                  </div>
                </form>
              </div>
              <div class="overflow-x-auto">
                <table class="table table-zebra w-full min-w-[600px]">
                <thead>
                  <tr>
                    <th class="text-gray-700 font-bold">Date</th>
                    <th class="text-gray-700 font-bold">Description</th>
                    <th class="text-gray-700 font-bold">Category</th>
                    <th class="text-right text-gray-700 font-bold">Amount</th>
                    <th class="text-center text-gray-700 font-bold">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="t in transactions.data" :key="t.id" class="hover:bg-gray-50 transition-colors">
                    <td class="text-gray-800">{{ t.entry_date }}</td>
                    <td>
                      <div class="font-medium text-gray-800">{{ t.description }}</div>
                      <div class="text-xs uppercase font-semibold text-gray-500">{{ t.type }}</div>
                    </td>
                    <td>
                      <span class="badge badge-outline text-gray-800">{{ t.category }}</span>
                    </td>
                    <td class="text-right font-bold" :style="{ color: t.type === 'income' ? '#16a34a' : '#dc2626' }">
                      {{ t.type === 'income' ? '+' : '-' }}₱{{ t.amount }}
                    </td>
                    <td class="text-center">
                      <div class="flex gap-2 justify-center">
                        <Link
                          :href="route('transactions.edit', t.id)"
                          class="btn btn-ghost btn-sm btn-square"
                          title="Edit Transaction"
                        >
                          <!-- SVG icon -->
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                          </svg>
                        </Link>
                        <button
                          @click="deleteTransaction(t.id)"
                          class="btn btn-ghost btn-sm btn-square text-error"
                          title="Delete Transaction"
                        >
                          <!-- SVG icon -->
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </button>
                      </div>
                    </td>
                  </tr>
                  <tr v-if="!transactions.data || transactions.data.length === 0">
                    <td colspan="5" class="p-10 text-center text-gray-500">
                      No transactions found yet.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        </template>
    </main>
  </div>
  </AuthenticatedLayout>
</template>

<script setup>
import { ref, computed } from 'vue';
import AddTransaction from './AddTransaction.vue';
const showAddTransaction = ref(false);
  <AddTransaction v-if="showAddTransaction" :categories="categories" @close="showAddTransaction = false" />
import { ref, computed } from 'vue';
import { Head, Link, useForm, router } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import LineChart from '@/Components/LineChart.vue';
import PieChart from '@/Components/PieChart.vue';

const props = defineProps({
  auth: Object,
  transactions: Object,
  summary: Object,
  categories: Array,
  expenseTotals: Array,
  incomeTotals: Array,
  filters: Object,
});

const tab = ref('dashboard');
const filters = ref({ ...props.filters });

const barChartData = computed(() =>
  props.categories.map((cat, idx) => ({
    category: cat,
    income: props.incomeTotals[idx] || 0,
    expense: props.expenseTotals[idx] || 0,
  }))
);

const expenseByCategory = computed(() => {
  const result = {};
  (props.transactions.data || []).forEach((t) => {
    if (t.type === 'expense') {
      if (!result[t.category]) result[t.category] = 0;
      result[t.category] += Number(t.amount);
    }
  });
  return result;
});

const pieChartData = computed(() =>
  Object.entries(expenseByCategory.value).map(([name, value]) => ({ name, value }))
);

const lineData = computed(() => {
  const dateMap = {};
  (props.transactions.data || []).forEach((t) => {
    const date = t.entry_date;
    if (!dateMap[date]) dateMap[date] = { date, income: 0, expense: 0 };
    if (t.type === 'income') {
      dateMap[date].income += parseFloat(t.amount);
    } else {
      dateMap[date].expense += parseFloat(t.amount);
    }
  });
  return Object.values(dateMap).sort((a, b) => a.date.localeCompare(b.date));
});

function applyFilters() {
  router.get(route('dashboard'), { ...filters.value });
}
function clearFilters() {
  filters.value = {};
  router.get(route('dashboard'));
}
function deleteTransaction(id) {
  if (confirm('Are you sure you want to delete this transaction?')) {
    router.delete(route('transactions.destroy', id));
  }
}
</script>

<style scoped>
/* Responsive tweaks for dashboard */
.stat-title {
  font-size: 1rem;
}
.stat-value {
  font-size: 2rem;
}
@media (max-width: 640px) {
  .stat-value {
    font-size: 1.25rem;
  }
  .stat-title {
    font-size: 0.9rem;
  }
}
</style>

// resources/js/Pages/Dashboard.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm, router, Link } from '@inertiajs/react';
import InputLabel from '@/Components/InputLabel';
import TextInput from '@/Components/TextInput';
import InputError from '@/Components/InputError';
import PrimaryButton from '@/Components/PrimaryButton';

// Recharts components for modern, responsive charts
import {
    ResponsiveContainer,
    BarChart,
    Bar,
    PieChart,
    Pie,
    Cell,
    XAxis,
    YAxis,
    Tooltip as ReTooltip,
    Legend as ReLegend,
} from 'recharts';

// color palettes
const incomeColor = '#22d399';
const expenseColor = '#ef4444';
const pieColors = ['#6366f1', '#ec4899', '#22d3ee', '#facc15', '#34d399', '#f87171'];

export default function Dashboard({ auth, transactions, summary, categories, expenseTotals, incomeTotals }) {
    
    // Inertia Form Hook
    const { data, setData, post, processing, reset, errors } = useForm({
        description: '',
        amount: '',
        type: 'expense',
        category: 'Food',
        entry_date: new Date().toISOString().split('T')[0],
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('transactions.store'), {
            onSuccess: () => reset(),
        });
    };

    // prepare dataset for Recharts bar chart. each entry is {category, income, expense}
    const barChartData = categories.map((cat, idx) => ({
        category: cat,
        income: incomeTotals[idx] || 0,
        expense: expenseTotals[idx] || 0,
    }));

    // prepare data for pie chart (e.g. expenses only, could easily extend)
    const pieChartData = categories.map((cat, idx) => ({
        name: cat,
        value: expenseTotals[idx] || 0,
    }));
    return (
        <AuthenticatedLayout user={auth.user}>
            <Head title="Dashboard" />

            <div className="py-12 px-4 max-w-7xl mx-auto space-y-6">
                
                {/* 1. Summary Cards using DaisyUI stats */}
                <div className="stats shadow">
                    <div className="stat">
                        <div className="stat-title">Total Income</div>
                        <div className="stat-value text-green-600">${summary.income}</div>
                    </div>
                    <div className="stat">
                        <div className="stat-title">Total Expenses</div>
                        <div className="stat-value text-red-600">${summary.expense}</div>
                    </div>
                    <div className="stat">
                        <div className="stat-title">Total Revenue</div>
                        <div className="stat-value">${summary.balance}</div>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* 2. Add Transaction Form */}
                    <div className="card bg-base-100 shadow lg:col-span-1">
                        <div className="card-body">
                            <h3 className="font-bold mb-4 text-lg">Add Transaction</h3>
                            <form onSubmit={submit} className="space-y-4">
                                <div className="form-control">
                                    <InputLabel value="Description" htmlFor="description" />
                                    <TextInput
                                        id="description"
                                        type="text"
                                        placeholder="Description"
                                        value={data.description}
                                        onChange={(e) => setData('description', e.target.value)}
                                    />
                                    {errors.description && (
                                        <InputError message={errors.description} />
                                    )}
                                </div>

                                <div className="flex gap-4">
                                    <div className="form-control flex-1">
                                        <InputLabel value="Amount" htmlFor="amount" />
                                        <TextInput
                                            id="amount"
                                            type="number"
                                            step="0.01"
                                            min="0"
                                            placeholder="0.00"
                                            value={data.amount}
                                            onChange={(e) => setData('amount', e.target.value)}
                                        />
                                        {errors.amount && (
                                            <InputError message={errors.amount} />
                                        )}
                                    </div>
                                    <div className="form-control flex-1">
                                        <InputLabel value="Type" htmlFor="type" />
                                        <select
                                            id="type"
                                            className="select select-bordered w-full"
                                            value={data.type}
                                            onChange={(e) => setData('type', e.target.value)}
                                        >
                                            <option value="income">Income</option>
                                            <option value="expense">Expense</option>
                                        </select>
                                        {errors.type && (
                                            <InputError message={errors.type} />
                                        )}
                                    </div>
                                </div>

                                <div className="flex gap-4">
                                    <div className="form-control flex-1">
                                        <InputLabel value="Category" htmlFor="category" />
                                        <select
                                            id="category"
                                            className="select select-bordered w-full"
                                            value={data.category}
                                            onChange={(e) => setData('category', e.target.value)}
                                        >
                                            <option value="Food">Food</option>
                                            <option value="Salary">Salary</option>
                                            <option value="Rent">Rent</option>
                                            <option value="Leisure">Leisure</option>
                                            <option value="Bills">Bills</option>
                                        </select>
                                        {errors.category && (
                                            <InputError message={errors.category} />
                                        )}
                                    </div>
                                    <div className="form-control flex-1">
                                        <InputLabel value="Date" htmlFor="entry_date" />
                                        <input
                                            id="entry_date"
                                            type="date"
                                            className="input input-bordered w-full"
                                            value={data.entry_date}
                                            onChange={(e) => setData('entry_date', e.target.value)}
                                        />
                                        {errors.entry_date && (
                                            <InputError message={errors.entry_date} />
                                        )}
                                    </div>
                                </div>

                                <PrimaryButton
                                    type="submit"
                                    className="w-full"
                                    disabled={processing}
                                >
                                    Save Transaction
                                </PrimaryButton>
                            </form>
                        </div>
                    </div>

                    {/* 3. Category Breakdown Chart */}
                    <div className="card bg-base-100 shadow lg:col-span-2 h-96 p-6">
                        <h3 className="font-bold mb-4 text-lg text-center">Category Breakdown</h3>
                        {(categories && categories.length > 0) ? (
                            <div className="w-full h-full">
                                <ResponsiveContainer width="100%" height="100%">
                                    <BarChart data={barChartData} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
                                        <XAxis dataKey="category" tick={{ fill: '#374151' }} />
                                        <YAxis tick={{ fill: '#374151' }} />
                                        <ReTooltip />
                                        <ReLegend verticalAlign="bottom" />
                                        <Bar dataKey="income" name="Income" fill={incomeColor} barSize={50} />
                                        <Bar dataKey="expense" name="Expense" fill={expenseColor} barSize={50} />
                                    </BarChart>
                                </ResponsiveContainer>
                            </div>
                        ) : (
                            <p className="text-gray-400 mt-10">Add transactions to see the chart</p>
                        )}
                    </div>
                </div>

                {/* 4. Transaction History Table */}
                <div className="card bg-base-100 shadow overflow-x-auto">
                    <div className="card-body">
                        <h3 className="font-bold mb-4 text-lg">Recent Transactions</h3>
                        <table className="table table-zebra w-full">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Description</th>
                                    <th>Category</th>
                                    <th className="text-right">Amount</th>
                                    <th className="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {transactions.length > 0 ? transactions.map((t) => (
                                    <tr key={t.id}>
                                        <td>{t.entry_date}</td>
                                        <td>
                                            <div className="font-medium">{t.description}</div>
                                            <div className="text-xs uppercase" style={{color: '#374151'}}>{t.type}</div>
                                        </td>
                                        <td>
                                            <span className="badge badge-outline">
                                                {t.category}
                                            </span>
                                        </td>
                                        <td className="text-right font-bold" style={{color: t.type === 'income' ? '#16a34a' : '#dc2626'}}>
                                            {t.type === 'income' ? '+' : '-'}${t.amount}
                                        </td>
                                        <td className="text-center">
                                            <div className="flex gap-2 justify-center">
                                                <Link
                                                    href={route('transactions.edit', t.id)}
                                                    className="btn btn-ghost btn-sm btn-square"
                                                    title="Edit Transaction"
                                                >
                                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                                    </svg>
                                                </Link>
                                                <button 
                                                    onClick={() => {
                                                        if(confirm('Are you sure you want to delete this transaction?')) {
                                                            router.delete(route('transactions.destroy', t.id))
                                                        }
                                                    }}
                                                    className="btn btn-ghost btn-sm btn-square text-error"
                                                    title="Delete Transaction"
                                                >
                                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                    </svg>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                )) : (
                                    <tr>
                                        <td colSpan="5" className="p-10 text-center text-gray-600 dark:text-gray-500">
                                            No transactions found yet.
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
