// resources/js/Pages/Auth/Register.jsx
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Head, Link, useForm } from '@inertiajs/react';

// Modern minimalist registration page for brand new users.
// The form is managed by Inertia's `useForm` hook.
export default function Register() {
    // useForm hook manages all form state and submission logic
    const { data, setData, post, processing, errors, reset } = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    // Handle form submission
    const submit = (e) => {
        e.preventDefault();

        post(route('register'), {
            // clear password fields after attempt for security
            onFinish: () => reset('password', 'password_confirmation'),
        });
    };

    return (
        <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100 px-4 py-12">
            <Head title="Register" />

            {/* Main registration card container */}
            <div className="w-full max-w-md">
                {/* Header section with title and description */}
                <div className="mb-8 text-center">
                    <h1 className="text-3xl font-bold text-gray-900">Create Account</h1>
                    <p className="mt-2 text-sm text-gray-600">Join us to get started</p>
                </div>

                {/* White card with subtle shadow and border */}
                <div className="rounded-lg bg-white px-8 py-8 shadow-sm ring-1 ring-gray-200">
                    <form onSubmit={submit} className="space-y-5">
                        {/* Full name input field */}
                        <div>
                            <InputLabel htmlFor="name" value="Full Name" />
                            <TextInput
                                id="name"
                                type="text"
                                name="name"
                                value={data.name}
                                className="mt-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                autoComplete="name"
                                isFocused={true}
                                onChange={(e) => setData('name', e.target.value)}
                                placeholder="John Doe"
                                required
                            />
                            <InputError message={errors.name} className="mt-1" />
                        </div>

                        {/* Email input field */}
                        <div>
                            <InputLabel htmlFor="email" value="Email Address" />
                            <TextInput
                                id="email"
                                type="email"
                                name="email"
                                value={data.email}
                                className="mt-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                autoComplete="email"
                                onChange={(e) => setData('email', e.target.value)}
                                placeholder="you@example.com"
                                required
                            />
                            <InputError message={errors.email} className="mt-1" />
                        </div>

                        {/* Password input field */}
                        <div>
                            <InputLabel htmlFor="password" value="Password" />
                            <TextInput
                                id="password"
                                type="password"
                                name="password"
                                value={data.password}
                                className="mt-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                autoComplete="new-password"
                                onChange={(e) => setData('password', e.target.value)}
                                placeholder="••••••••"
                                required
                            />
                            <InputError message={errors.password} className="mt-1" />
                        </div>

                        {/* Password confirmation field */}
                        <div>
                            <InputLabel
                                htmlFor="password_confirmation"
                                value="Confirm Password"
                            />
                            <TextInput
                                id="password_confirmation"
                                type="password"
                                name="password_confirmation"
                                value={data.password_confirmation}
                                className="mt-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                autoComplete="new-password"
                                onChange={(e) =>
                                    setData('password_confirmation', e.target.value)
                                }
                                placeholder="••••••••"
                                required
                            />
                            <InputError
                                message={errors.password_confirmation}
                                className="mt-1"
                            />
                        </div>

                        {/* Register button - shows loading state while processing */}
                        <PrimaryButton
                            className="w-full py-2.5 font-medium"
                            disabled={processing}
                        >
                            {processing ? 'Creating account...' : 'Create Account'}
                        </PrimaryButton>
                    </form>

                    {/* Footer section - link back to login */}
                    <div className="mt-6 border-t border-gray-200 pt-6">
                        <p className="text-center text-sm text-gray-600">
                            Already have an account?{' '}
                            <Link
                                href={route('login')}
                                className="font-medium text-indigo-600 hover:text-indigo-700 transition-colors"
                            >
                                Sign in
                            </Link>
                        </p>
                    </div>
                </div>

                {/* Footer disclaimer text */}
                <p className="mt-6 text-center text-xs text-gray-500">
                    By creating an account, you agree to our terms of service
                </p>
            </div>
        </div>
    );
}

// resources/js/Pages/Auth/Register.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-base-200 px-4 py-12">
    <Head title="Register" />
    <div class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold">Create Account</h1>
        <p class="text-sm">Join us to get started</p>
      </div>
      <div class="card shadow-lg">
        <div class="card-body">
          <form @submit.prevent="submit" class="space-y-5">
            <div>
              <InputLabel htmlFor="name" value="Full Name" />
              <TextInput
                id="name"
                type="text"
                name="name"
                v-model="form.name"
                autocomplete="name"
                :isFocused="true"
                placeholder="John Doe"
                required
              />
              <InputError :message="errors.name" class="mt-1" />
            </div>
            <div>
              <InputLabel htmlFor="email" value="Email Address" />
              <TextInput
                id="email"
                type="email"
                name="email"
                v-model="form.email"
                autocomplete="email"
                placeholder="you@example.com"
                required
              />
              <InputError :message="errors.email" class="mt-1" />
            </div>
            <div>
              <InputLabel htmlFor="password" value="Password" />
              <TextInput
                id="password"
                type="password"
                name="password"
                v-model="form.password"
                autocomplete="new-password"
                placeholder="••••••••"
                required
              />
              <InputError :message="errors.password" class="mt-1" />
            </div>
            <div>
              <InputLabel htmlFor="password_confirmation" value="Confirm Password" />
              <TextInput
                id="password_confirmation"
                type="password"
                name="password_confirmation"
                v-model="form.password_confirmation"
                autocomplete="new-password"
                placeholder="••••••••"
                required
              />
              <InputError :message="errors.password_confirmation" class="mt-1" />
            </div>
            <PrimaryButton class="w-full" :disabled="processing">
              {{ processing ? 'Creating account...' : 'Create Account' }}
            </PrimaryButton>
          </form>
          <div class="divider">OR</div>
          <p class="text-center text-sm">
            Already have an account?
            <Link :href="route('login')" class="underline">Sign in</Link>
          </p>
        </div>
      </div>
      <p class="mt-6 text-center text-xs">
        By creating an account, you agree to our terms of service
      </p>
    </div>
  </div>
</template>

<script setup>
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';

const form = ref({
  name: '',
  email: '',
  password: '',
  password_confirmation: ''
});
const errors = ref({});
const processing = ref(false);

function submit() {
  processing.value = true;
  // Use Inertia form post
  // You may need to adjust this to useForm if you want validation, etc.
  // For now, use router.post for simplicity
  window.route('register'); // ensure route helper is available
  // Simulate Inertia post (replace with useForm if needed)
  // router.post(route('register'), form.value, ...)
  // For now, just set processing to false after a delay
  setTimeout(() => {
    processing.value = false;
  }, 1000);
}
</script>

<style scoped>
</style>
